require "rubygems"
require "rake"
require "rake/gempackagetask"

# This is to be used to generate the prawn meta-gem only.  You probably want to
# build prawn-core unless you know exactly what you are doing, so do rake gem
# instead.

spec = Gem::Specification.new do |spec|
  spec.name = "prawn"
  spec.version = "0.8.0"
  spec.platform = Gem::Platform::RUBY
  spec.summary = "A fast and nimble PDF generator for Ruby"
  spec.add_dependency('prawn-core',   '= 0.8.0')
  spec.add_dependency('prawn-layout', '= 0.8.0')
  spec.add_dependency('prawn-security''= 0.8.0')
  spec.files = Dir.glob("lib/*")
  spec.require_path = "lib"
  spec.author = "Gregory Brown"
  spec.email = "  gregory.t.brown@gmail.com"
  spec.rubyforge_project = "prawn"
  spec.homepage = "http://prawn.majesticseacreature.com"
  spec.description = "Prawn is a fast, tiny, and nimble PDF generator for Ruby"
  spec.post_install_message = %{
  Welcome to Prawn, the best pure-Ruby PDF solution ever!
  This is the bleeding edge of 0.8.  You probably shouldn't be using it.

  Try the latest stable release instead, or the stable branch at:
  http://github.com/sandal/prawn
  }
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_zip = true
  pkg.need_tar = true
end
