require "prawn/core/text/formatted/line_wrap"
require "prawn/core/text/formatted/arranger"
require "prawn/text/formatted/box"
require "prawn/text/formatted/parser"
require "prawn/text/formatted/fragment"
